# Generated by Django 3.1 on 2023-06-21 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_variatrionmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VariatrionManager',
        ),
    ]
